- name: Post Image Card to Google Chat
        run: |
          IMAGE_URL="https://github.com/${{ github.repository }}/releases/download/latest/output.png?v=$(date +%s)"
          
          cat <<EOF > payload.json
          {
            "cardsV2": [{
              "cardId": "cashFlowTableCard",
              "card": {
                "sections": [{
                  "widgets": [{
                    "image": {
                      "imageUrl": "${IMAGE_URL}",
                      "altText": "Cash Flow Table Image",
                      "onClick": {
                        "openLink": {
                          "url": "${IMAGE_URL}"
                        }
                      }
                    }
                  }]
                }]
              }
            }]
          }
          EOF

          curl -X POST -H "Content-Type: application/json" -d @payload.json "${{ github.event.client_payload.webhook_url }}"
